export default ['Accounting software',
    'ADP Workforce Now',
    'Analytical software',
    'Auditing',
    'Budget forecasting',
    'Cash flow analysis',
    'Cost accounting',
    'Credit/debt management',
    'Estate planning',
    'Financial accounting',
    'Financial compliance',
    'Financial reporting',
    'Forensic accounting',
    'Google Sheets',
    'Income tax planning',
    'Intuit QuickBooks',
    'Management accounting',
    'Microsoft Excel',
    'Netsuite',
    'Payroll management',
    'PeopleSoft',
    'Reconciliation',
    'Revenue forecasting',
    'SAS',
    'SPSS Statistics',
    'Tax preparation',
    'Administrative support',
    'Booking travel',
    'Calendaring',
    'Customer service',
    'Google Workspace',
    'Meeting coordination',
    'Meeting minutes recording',
    'Office support',
    'Proofreading',
    'Scheduling',
    'Social media management',
    'Video conferencing software',
    'Zoom',
    'Agile',
    'Application scaling',
    'Back-end framework',
    'Back-end programming languages',
    'Database administration',
    'Front-end web technologies',
    'Hosting environment',
    'Java',
    'Load changes',
    'PHP',
    'Python',
    'Ruby',
    'Scrum',
    'Security compliance',
    'SQL',
    'Version control',
    'Git',
    'Account management',
    'Chat support',
    'CRM',
    'Language skills',
    'Phone support',
    'Resolutions',
    'Salesforce',
    'Ticketing',
    'Training',
    'Apache Hadoop and Spark',
    'AWS software',
    'Azure',
    'Coding',
    'Data cleaning',
    'Data modeling',
    'Data sampling',
    'Data structure',
    'Git and GitHub',
    'Keras',
    'Key libraries',
    'Microsoft Excel',
    'NumPy',
    'pandas',
    'Python',
    'PyTorch',
    'R',
    'SAS',
    'Scikit-learn',
    'Statistics',
    'Tableau',
    'TensorFlow',
    'The MathWorks MATLAB',
    'UNIX command line',
    'Budgeting',
    'Corporate communications',
    'Editing and proofreading',
    'Meeting coordination',
    'Preparing agendas',
    'Report generation',
    'Reviewing contracts',
    'Scheduling',
    'Zoom',
    'Microsoft Dynamics',
    'Montgomery Investment Technology FinTools',
    'Montgomery Investment Technology Utility XL',
    'NetSuite',
    'Oracle Business Intelligence',
    'S&P Capital IQ',
    'SAP software',
    'SAS Financial Management',
    'APIs',
    'Back-end data display',
    'CSS',
    'Dynamic web page design',
    'Framework templates',
    'HTML',
    'JavaScript',
    'Node.js',
    'React',
    'Search engine optimization (SEO)',
    'Software workflow',
    'Styling and color design',
    'Web page creation',
    'Website content display',
    'Website navigation optimization',
    'CircleCI',
    'Docker',
    'Go',
    'Node',
    'Postgres',
    'Python',
    'Rails',
    'Redux',
    'Ruby',
    'SASS',
    'Tornado',
    'TypeScript',
    'After Effects',
    'Autodesk AutoCAD',
    'Concepts',
    'Data visualization',
    'Design principles',
    'Dreamweaver',
    'Figma',
    'Illustrator',
    'InDesign',
    'InVision',
    'Microsoft Office Suite',
    'Photoshop',
    'Product Design',
    'Sketch',
    'Typography',
    'Wordpress',
    'Applicant tracking systems (ATS)',
    'Benefits administration and management',
    'Benchmarking',
    'Candidate screening',
    'Climate surveys',
    'Conducting background and reference checks',
    'Conflict resolution and management',
    'Contract negotiations',
    'Human resource information systems (HRIS)',
    'Interviewing',
    'Legal and regulatory compliance',
    'Onboarding',
    'Organizational development',
    'Orientation',
    'Payroll administration and management',
    'PeopleSoft',
    'Performance improvement and management',
    'Recruitment',
    'Sourcing',
    'Vendor negotiation',
    'Writing and posting job descriptions',
    'Adobe Creative Cloud',
    'Audience building',
    'Blog writing',
    'Brand management',
    'Content creation',
    'Content marketing',
    'Conversion rate optimization',
    'Customer acquisition',
    'Copywriting',
    'Data analysis',
    'Demand generation',
    'Digital marketing',
    'Email marketing',
    'Facebook management',
    'Google Ads',
    'Google Analytics',
    'Instagram management',
    'Lead generation',
    'LinkedIn management',
    'Marketing automation and technology',
    'Market research',
    'Marketo marketing automation',
    'Power editor',
    'Project management',
    'Search engine marketing (SEM)',
    'Social media',
    'TikTok management',
    'Twitter management',
    'Billing software',
    'Document management',
    'Executive support',
    'Expense reporting',
    'Facilities management',
    'Inventory management',
    'Invoicing',
    'Meeting coordination',
    'Office supply management',
    'Payroll processing',
    'Reports generation',
    'Vendor management',
    'ADA compliance',
    'Asana',
    'Axure',
    'Balsamiq',
    'Confluence',
    'Crashlytics',
    'Google Design Sprint Method',
    'Jira',
    'Justinmind',
    'Omnigraffle',
    'Story mapping',
    'Testflight',
    'Trello',
    'Ubertesting',
    'Xcode',
    'Zeplin',
    'A/B Testing',
    'Beta testing',
    'Customer analysis',
    'Data analytics',
    'Financial analysis',
    'Forecasting',
    'Kanban',
    'Quality assurance',
    'Release management',
    'Risk management',
    'Roadmapping',
    'Scrum management',
    'SWOT analysis',
    'Troubleshooting',
    'User research',
    'UX/UI design',
    'Waterfall',
    'ZenDesk',
    'Change management',
    'Client communication',
    'Deployment management',
    'Development and testing',
    'Impact assessment',
    'Microsoft Project',
    'Process development',
    'Process improvement',
    'Project life cycle',
    'Project management software',
    'Quality control',
    'Resource allocation',
    'Scheduling and planning',
    'Scope management',
    'Stakeholder management',
    'Business analysis',
    'Business development',
    'Cold calling',
    'Consultative selling',
    'Customer relations',
    'Executive relationships',
    'Lead generation',
    'Prospecting',
    'Relationship management',
    'Blackboard',
    'Blended learning',
    'Canvas',
    'Character education',
    'Classroom management',
    'Collaborative environments',
    'Data-driven instruction',
    'Inclusive classroom',
    'Interactive classroom',
    'MAP Testing',
    'Mystery Math',
    'Personalized learning',
    'Reading 3D',
    'Remote instruction',
    'Social-emotional learning',
    'Student-guided learning',
    'Application coding',
    'C++',
    'Command line tools',
    'Debugging',
    'Google Angular',
    'LAMP development',
    'Object-oriented design',
    'Responsive design',
    'Server-Side scripting',
    'Writing modules'
]